# Generated by Django 4.2.2 on 2024-02-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0032_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Retainer_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Customer_billing_address', models.CharField(blank=True, max_length=10, null=True)),
                ('Customer_gst_type', models.CharField(blank=True, max_length=10, null=True)),
                ('Customer_gstin', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Customer_place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('Retainer_Invoice_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Retainer_Invoice_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Expiration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Reference_number', models.IntegerField(null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=10, null=True)),
                ('Cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('UPI_number', models.CharField(blank=True, max_length=100, null=True)),
                ('Bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Document', models.FileField(blank=True, upload_to='file/retinv')),
                ('Sub_total', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('Shipping_charge', models.FloatField(blank=True, null=True)),
                ('Adjustment', models.FloatField(blank=True, default=0, null=True)),
                ('Grand_total', models.FloatField(blank=True, null=True)),
                ('Paid_amount', models.FloatField(default=0, max_length=100, null=True)),
                ('Balance', models.FloatField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('SENT', 'SENT')], max_length=150, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Payment_Terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finsys_App.fin_company_payment_terms')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Retainer_Invoice_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_no', models.BigIntegerField()),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Retainer_Invoice_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSN', models.CharField(max_length=100, null=True)),
                ('Quantity', models.IntegerField(default=0, null=True)),
                ('Price', models.CharField(max_length=100, null=True)),
                ('Discription', models.CharField(max_length=100, null=True)),
                ('Total', models.FloatField(max_length=100, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Ret_Inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_retainer_invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Retainer_Invoice_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Ret_Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_retainer_invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Invoice_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Ret_Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_retainer_invoice')),
            ],
        ),
    ]
