# Generated by Django 4.2.2 on 2024-02-27 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0033_fin_retainer_invoice_fin_retainer_invoice_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_retainer_invoice_items',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice_items',
            name='LoginDetails',
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
    ]
