# Generated by Django 4.2.2 on 2024-02-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0034_remove_fin_retainer_invoice_items_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_retainer_invoice_items',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details'),
        ),
        migrations.AddField(
            model_name='fin_retainer_invoice_items',
            name='LoginDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details'),
        ),
    ]
