# Generated by Django 4.2.2 on 2024-02-28 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0035_fin_retainer_invoice_items_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_retainer_invoice',
            name='Expiration_date',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice',
            name='Payment_Terms',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice',
            name='Shipping_charge',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='fin_retainer_invoice',
            name='sgst',
        ),
        migrations.AddField(
            model_name='fin_retainer_invoice_items',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 28)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 28)),
        ),
    ]
